extend the journald.conf template to cover all parameters
idiv-biodiversity/ansible-role-systemd-journald pull request #3
Opened 2021-04-16 10:37 UTC by kfiresmith

journald.conf.j2 now includes an optional role variable for each parameter
included with journald.  Additionally, I have added the configuration
file preamble included with the latest upstream journald release.

The templated file also now includes the {{ ansible_managed }}
standard heading.

Lastly, the README for the role was updated to cover this change.

fixes #2

2021-04-16 10:40 UTC, kfiresmith commented
Hi Christian,
Hopefully this PR looks a bit better than the one for timesyncd.  I read through the contribution guide and style guide, and believe I've gotten most of this correct, but please let me know if there are further areas where I can improve the quality of my PRs for your projects.

I found the overall git-knowledge-base page quite useful.  The only place I wasn't certain after reading was how to name my branch, so as you can see I named it 'extend-template'.  In hindsight, perhaps `topic/name` in the contribution guide would map to something more like `enhancement/extend-template`, or `bug/fix-typo`?

2021-04-19 15:30 UTC, wookietreiber commented
> I found the overall git-knowledge-base page quite useful. The only place I wasn't certain after reading was how to name my branch, so as you can see I named it 'extend-template'. In hindsight, perhaps topic/name in the contribution guide would map to something more like enhancement/extend-template, or bug/fix-typo?

Glad to hear you took a deeper dive into the knowledge base pages and that it's useful :smiley: 

Branch names aren't all too important if there aren't many of them and/or if they're short lived. Since this particular branch is only visible in your fork of the repository anyway, it's even less important. A good branch naming scheme, e.g. with the `topic/` prefix, can be extremely useful for truly shared and busy repositories, to which multiple people have push access. 

What's more important is preparing pull requests in a dedicated branch, so it's both easier to prepare multiple PRs at the same time and it's also easier to rebase if needed.

2021-04-19 15:44 UTC, wookietreiber requested changes
Mostly nitpicking. I have a certain style with my Markdown documents I haven't documented yet. Would be nice to have a review tool that does this automatically :smile:

2021-04-19 15:44 UTC, wookietreiber commented on README.md
> +Role variables include all supported journald parameters as documented in detail at the [freedesktop.org website](https://www.freedesktop.org/software/systemd/man/journald.conf.html#).
Please put the link into the link collection at the bottom of the README (consistency).

2021-04-19 15:44 UTC, wookietreiber commented on README.md
> +Because every parameter has a default, journald.conf starts completely commented out, until you choose to override a parameter default.
Please clarify that the defaults are from **journald**, not the **role**.

2021-04-19 15:44 UTC, wookietreiber commented on README.md
> +Role variables include all supported journald parameters as documented in detail at the [freedesktop.org website](https://www.freedesktop.org/software/systemd/man/journald.conf.html#).
Please hard wrap all lines to 79 characters (consistency).

2021-04-19 15:44 UTC, wookietreiber commented on README.md
> +Because every parameter has a default, journald.conf starts completely commented out, until you choose to override a parameter default.
Please put the code quotes around `journald.conf` (highlighting).

2021-04-19 15:46 UTC, wookietreiber commented
>  Additionally, I have added the configuration file preamble included with the latest upstream journald release.

That's awesome, I always do this, too, when I update a template. :+1:

2021-04-24 17:28 UTC, kfiresmith commented
Thanks for the feedback.  I've attempted to try to fix this PR/branch first before dealing with the other simple PR to update distro support.  I've gotten myself into a git mess and am possibly in over my head trying to update the PR.  
I tried firing up GitKraken to see if I could visually make sense of the mess I'm in, but that's somehow even worse.  Any advice on this?
![image](https://user-images.githubusercontent.com/8343629/115967492-e4138680-a500-11eb-9d61-1ceada03717b.png)

2021-04-26 14:43 UTC, wookietreiber commented
This is the classic **merge vs. rebase** or **linear vs. non-linear history** discussion. I assume that at some point you did a `git merge upstream/master` instead of `git rebase upstream/master`. I've written [a bit in the knowledge base about that](https://idiv-biodiversity.github.io/git-knowledge-base/master-collab.html), and I prefer rebase'ing over merging to create a [linear history](https://idiv-biodiversity.github.io/git-knowledge-base/linear-vs-nonlinear.html) in all my projects. 

You can fix this with rebase'ing on top off the current master. From your local repository, it should go like this: 

```bash
# for completeness
git remote add upstream https://github.com/idiv-biodiversity/ansible-role-systemd-journald.git

# perform the rebase 
git fetch upstream
git rebase upstream/master extend-template
git push --force-with-lease
```

I've tested this locally and the rebase had no conflicts. The force push should update the PR.

2021-05-08 10:57 UTC, kfiresmith commented
Hi @wookietreiber  - sadly this didn't work out for me, I think I'll have to start over.  I still have a detached head that seems to be marooned on it's own.

2021-05-08 11:03 UTC, kfiresmith commented
OK, bailed on the last detached head and tried again, and I see an updated commit now in this PR so please let me know if all conditions/changes are met at this point.  Thanks.

2021-05-31 09:50 UTC, wookietreiber commented
Sorry about the delay. I merged on the CLI, so will close here. I already cut a v1.0.0 release since we now support all parameters, thanks a lot for the contribution!

2021-05-31 09:50 UTC, closed without merging